/*
Future Vuls Public API

Future Vuls Public API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"os"
)

// CveGetCveDetailResponseBody struct for CveGetCveDetailResponseBody
type CveGetCveDetailResponseBody struct {
	// advisory of cve
	Advisories []AdvisoryResponseBody `json:"advisories,omitempty"`
	// created time
	CreatedAt time.Time `json:"createdAt"`
	// Cve ID string of cve
	CveID string `json:"cveID"`
	// cvss of cve
	Cvss *os.File `json:"cvss"`
	// cwes of cve
	Cwes []CweResponseBody `json:"cwes"`
	// envMetricV2 of cve
	EnvMetricV2s []EnvMetricV2ResponseBody `json:"envMetricV2s"`
	// envMetricV3 of cve
	EnvMetricV3s []EnvMetricV3ResponseBody `json:"envMetricV3s"`
	// references of cve
	References map[string]string `json:"references"`
	// secMetric of cve
	SecMetrics []SecMetricResponseBody `json:"secMetrics"`
	// serverOsFamilies of cve
	ServerOsFamilies []string `json:"serverOsFamilies"`
	TmpMetricV2 TmpMetricResponseBody `json:"tmpMetricV2"`
	TmpMetricV3 TmpMetricResponseBody `json:"tmpMetricV3"`
	// updated time
	UpdatedAt time.Time `json:"updatedAt"`
}

// NewCveGetCveDetailResponseBody instantiates a new CveGetCveDetailResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCveGetCveDetailResponseBody(createdAt time.Time, cveID string, cvss *os.File, cwes []CweResponseBody, envMetricV2s []EnvMetricV2ResponseBody, envMetricV3s []EnvMetricV3ResponseBody, references map[string]string, secMetrics []SecMetricResponseBody, serverOsFamilies []string, tmpMetricV2 TmpMetricResponseBody, tmpMetricV3 TmpMetricResponseBody, updatedAt time.Time) *CveGetCveDetailResponseBody {
	this := CveGetCveDetailResponseBody{}
	this.CreatedAt = createdAt
	this.CveID = cveID
	this.Cvss = cvss
	this.Cwes = cwes
	this.EnvMetricV2s = envMetricV2s
	this.EnvMetricV3s = envMetricV3s
	this.References = references
	this.SecMetrics = secMetrics
	this.ServerOsFamilies = serverOsFamilies
	this.TmpMetricV2 = tmpMetricV2
	this.TmpMetricV3 = tmpMetricV3
	this.UpdatedAt = updatedAt
	return &this
}

// NewCveGetCveDetailResponseBodyWithDefaults instantiates a new CveGetCveDetailResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCveGetCveDetailResponseBodyWithDefaults() *CveGetCveDetailResponseBody {
	this := CveGetCveDetailResponseBody{}
	return &this
}

// GetAdvisories returns the Advisories field value if set, zero value otherwise.
func (o *CveGetCveDetailResponseBody) GetAdvisories() []AdvisoryResponseBody {
	if o == nil || o.Advisories == nil {
		var ret []AdvisoryResponseBody
		return ret
	}
	return o.Advisories
}

// GetAdvisoriesOk returns a tuple with the Advisories field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CveGetCveDetailResponseBody) GetAdvisoriesOk() ([]AdvisoryResponseBody, bool) {
	if o == nil || o.Advisories == nil {
		return nil, false
	}
	return o.Advisories, true
}

// HasAdvisories returns a boolean if a field has been set.
func (o *CveGetCveDetailResponseBody) HasAdvisories() bool {
	if o != nil && o.Advisories != nil {
		return true
	}

	return false
}

// SetAdvisories gets a reference to the given []AdvisoryResponseBody and assigns it to the Advisories field.
func (o *CveGetCveDetailResponseBody) SetAdvisories(v []AdvisoryResponseBody) {
	o.Advisories = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *CveGetCveDetailResponseBody) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *CveGetCveDetailResponseBody) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *CveGetCveDetailResponseBody) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetCveID returns the CveID field value
func (o *CveGetCveDetailResponseBody) GetCveID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CveID
}

// GetCveIDOk returns a tuple with the CveID field value
// and a boolean to check if the value has been set.
func (o *CveGetCveDetailResponseBody) GetCveIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CveID, true
}

// SetCveID sets field value
func (o *CveGetCveDetailResponseBody) SetCveID(v string) {
	o.CveID = v
}

// GetCvss returns the Cvss field value
func (o *CveGetCveDetailResponseBody) GetCvss() *os.File {
	if o == nil {
		var ret *os.File
		return ret
	}

	return o.Cvss
}

// GetCvssOk returns a tuple with the Cvss field value
// and a boolean to check if the value has been set.
func (o *CveGetCveDetailResponseBody) GetCvssOk() (**os.File, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Cvss, true
}

// SetCvss sets field value
func (o *CveGetCveDetailResponseBody) SetCvss(v *os.File) {
	o.Cvss = v
}

// GetCwes returns the Cwes field value
func (o *CveGetCveDetailResponseBody) GetCwes() []CweResponseBody {
	if o == nil {
		var ret []CweResponseBody
		return ret
	}

	return o.Cwes
}

// GetCwesOk returns a tuple with the Cwes field value
// and a boolean to check if the value has been set.
func (o *CveGetCveDetailResponseBody) GetCwesOk() ([]CweResponseBody, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cwes, true
}

// SetCwes sets field value
func (o *CveGetCveDetailResponseBody) SetCwes(v []CweResponseBody) {
	o.Cwes = v
}

// GetEnvMetricV2s returns the EnvMetricV2s field value
func (o *CveGetCveDetailResponseBody) GetEnvMetricV2s() []EnvMetricV2ResponseBody {
	if o == nil {
		var ret []EnvMetricV2ResponseBody
		return ret
	}

	return o.EnvMetricV2s
}

// GetEnvMetricV2sOk returns a tuple with the EnvMetricV2s field value
// and a boolean to check if the value has been set.
func (o *CveGetCveDetailResponseBody) GetEnvMetricV2sOk() ([]EnvMetricV2ResponseBody, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnvMetricV2s, true
}

// SetEnvMetricV2s sets field value
func (o *CveGetCveDetailResponseBody) SetEnvMetricV2s(v []EnvMetricV2ResponseBody) {
	o.EnvMetricV2s = v
}

// GetEnvMetricV3s returns the EnvMetricV3s field value
func (o *CveGetCveDetailResponseBody) GetEnvMetricV3s() []EnvMetricV3ResponseBody {
	if o == nil {
		var ret []EnvMetricV3ResponseBody
		return ret
	}

	return o.EnvMetricV3s
}

// GetEnvMetricV3sOk returns a tuple with the EnvMetricV3s field value
// and a boolean to check if the value has been set.
func (o *CveGetCveDetailResponseBody) GetEnvMetricV3sOk() ([]EnvMetricV3ResponseBody, bool) {
	if o == nil {
		return nil, false
	}
	return o.EnvMetricV3s, true
}

// SetEnvMetricV3s sets field value
func (o *CveGetCveDetailResponseBody) SetEnvMetricV3s(v []EnvMetricV3ResponseBody) {
	o.EnvMetricV3s = v
}

// GetReferences returns the References field value
func (o *CveGetCveDetailResponseBody) GetReferences() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.References
}

// GetReferencesOk returns a tuple with the References field value
// and a boolean to check if the value has been set.
func (o *CveGetCveDetailResponseBody) GetReferencesOk() (*map[string]string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.References, true
}

// SetReferences sets field value
func (o *CveGetCveDetailResponseBody) SetReferences(v map[string]string) {
	o.References = v
}

// GetSecMetrics returns the SecMetrics field value
func (o *CveGetCveDetailResponseBody) GetSecMetrics() []SecMetricResponseBody {
	if o == nil {
		var ret []SecMetricResponseBody
		return ret
	}

	return o.SecMetrics
}

// GetSecMetricsOk returns a tuple with the SecMetrics field value
// and a boolean to check if the value has been set.
func (o *CveGetCveDetailResponseBody) GetSecMetricsOk() ([]SecMetricResponseBody, bool) {
	if o == nil {
		return nil, false
	}
	return o.SecMetrics, true
}

// SetSecMetrics sets field value
func (o *CveGetCveDetailResponseBody) SetSecMetrics(v []SecMetricResponseBody) {
	o.SecMetrics = v
}

// GetServerOsFamilies returns the ServerOsFamilies field value
func (o *CveGetCveDetailResponseBody) GetServerOsFamilies() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.ServerOsFamilies
}

// GetServerOsFamiliesOk returns a tuple with the ServerOsFamilies field value
// and a boolean to check if the value has been set.
func (o *CveGetCveDetailResponseBody) GetServerOsFamiliesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ServerOsFamilies, true
}

// SetServerOsFamilies sets field value
func (o *CveGetCveDetailResponseBody) SetServerOsFamilies(v []string) {
	o.ServerOsFamilies = v
}

// GetTmpMetricV2 returns the TmpMetricV2 field value
func (o *CveGetCveDetailResponseBody) GetTmpMetricV2() TmpMetricResponseBody {
	if o == nil {
		var ret TmpMetricResponseBody
		return ret
	}

	return o.TmpMetricV2
}

// GetTmpMetricV2Ok returns a tuple with the TmpMetricV2 field value
// and a boolean to check if the value has been set.
func (o *CveGetCveDetailResponseBody) GetTmpMetricV2Ok() (*TmpMetricResponseBody, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TmpMetricV2, true
}

// SetTmpMetricV2 sets field value
func (o *CveGetCveDetailResponseBody) SetTmpMetricV2(v TmpMetricResponseBody) {
	o.TmpMetricV2 = v
}

// GetTmpMetricV3 returns the TmpMetricV3 field value
func (o *CveGetCveDetailResponseBody) GetTmpMetricV3() TmpMetricResponseBody {
	if o == nil {
		var ret TmpMetricResponseBody
		return ret
	}

	return o.TmpMetricV3
}

// GetTmpMetricV3Ok returns a tuple with the TmpMetricV3 field value
// and a boolean to check if the value has been set.
func (o *CveGetCveDetailResponseBody) GetTmpMetricV3Ok() (*TmpMetricResponseBody, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TmpMetricV3, true
}

// SetTmpMetricV3 sets field value
func (o *CveGetCveDetailResponseBody) SetTmpMetricV3(v TmpMetricResponseBody) {
	o.TmpMetricV3 = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *CveGetCveDetailResponseBody) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *CveGetCveDetailResponseBody) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *CveGetCveDetailResponseBody) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o CveGetCveDetailResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Advisories != nil {
		toSerialize["advisories"] = o.Advisories
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if true {
		toSerialize["cveID"] = o.CveID
	}
	if true {
		toSerialize["cvss"] = o.Cvss
	}
	if true {
		toSerialize["cwes"] = o.Cwes
	}
	if true {
		toSerialize["envMetricV2s"] = o.EnvMetricV2s
	}
	if true {
		toSerialize["envMetricV3s"] = o.EnvMetricV3s
	}
	if true {
		toSerialize["references"] = o.References
	}
	if true {
		toSerialize["secMetrics"] = o.SecMetrics
	}
	if true {
		toSerialize["serverOsFamilies"] = o.ServerOsFamilies
	}
	if true {
		toSerialize["tmpMetricV2"] = o.TmpMetricV2
	}
	if true {
		toSerialize["tmpMetricV3"] = o.TmpMetricV3
	}
	if true {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableCveGetCveDetailResponseBody struct {
	value *CveGetCveDetailResponseBody
	isSet bool
}

func (v NullableCveGetCveDetailResponseBody) Get() *CveGetCveDetailResponseBody {
	return v.value
}

func (v *NullableCveGetCveDetailResponseBody) Set(val *CveGetCveDetailResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCveGetCveDetailResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCveGetCveDetailResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCveGetCveDetailResponseBody(val *CveGetCveDetailResponseBody) *NullableCveGetCveDetailResponseBody {
	return &NullableCveGetCveDetailResponseBody{value: val, isSet: true}
}

func (v NullableCveGetCveDetailResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCveGetCveDetailResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


