/*
Future Vuls Public API

Future Vuls Public API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// EnvMetricV3ResponseBody EnvMetricV3 describes a envMetricV3
type EnvMetricV3ResponseBody struct {
	// created time
	CreatedAt time.Time `json:"createdAt"`
	// CveID of envMetricV3
	CveID string `json:"cveID"`
	// MA of envMetricV3
	Ma string `json:"ma"`
	// MAC of envMetricV3
	Mac string `json:"mac"`
	// MAV of envMetricV3
	Mav string `json:"mav"`
	// MC of envMetricV3
	Mc string `json:"mc"`
	// MPR of envMetricV3
	Mpr string `json:"mpr"`
	// MS of envMetricV3
	Ms string `json:"ms"`
	// MUI of envMetricV3
	Mui string `json:"mui"`
	// ServerRoleID of envMetricV3
	RoleID int64 `json:"roleID"`
	// ServerRoleName of envMetricV3
	RoleName string `json:"roleName"`
	// updated time
	UpdatedAt time.Time `json:"updatedAt"`
}

// NewEnvMetricV3ResponseBody instantiates a new EnvMetricV3ResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnvMetricV3ResponseBody(createdAt time.Time, cveID string, ma string, mac string, mav string, mc string, mpr string, ms string, mui string, roleID int64, roleName string, updatedAt time.Time) *EnvMetricV3ResponseBody {
	this := EnvMetricV3ResponseBody{}
	this.CreatedAt = createdAt
	this.CveID = cveID
	this.Ma = ma
	this.Mac = mac
	this.Mav = mav
	this.Mc = mc
	this.Mpr = mpr
	this.Ms = ms
	this.Mui = mui
	this.RoleID = roleID
	this.RoleName = roleName
	this.UpdatedAt = updatedAt
	return &this
}

// NewEnvMetricV3ResponseBodyWithDefaults instantiates a new EnvMetricV3ResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnvMetricV3ResponseBodyWithDefaults() *EnvMetricV3ResponseBody {
	this := EnvMetricV3ResponseBody{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *EnvMetricV3ResponseBody) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *EnvMetricV3ResponseBody) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *EnvMetricV3ResponseBody) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetCveID returns the CveID field value
func (o *EnvMetricV3ResponseBody) GetCveID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CveID
}

// GetCveIDOk returns a tuple with the CveID field value
// and a boolean to check if the value has been set.
func (o *EnvMetricV3ResponseBody) GetCveIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CveID, true
}

// SetCveID sets field value
func (o *EnvMetricV3ResponseBody) SetCveID(v string) {
	o.CveID = v
}

// GetMa returns the Ma field value
func (o *EnvMetricV3ResponseBody) GetMa() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ma
}

// GetMaOk returns a tuple with the Ma field value
// and a boolean to check if the value has been set.
func (o *EnvMetricV3ResponseBody) GetMaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ma, true
}

// SetMa sets field value
func (o *EnvMetricV3ResponseBody) SetMa(v string) {
	o.Ma = v
}

// GetMac returns the Mac field value
func (o *EnvMetricV3ResponseBody) GetMac() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mac
}

// GetMacOk returns a tuple with the Mac field value
// and a boolean to check if the value has been set.
func (o *EnvMetricV3ResponseBody) GetMacOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mac, true
}

// SetMac sets field value
func (o *EnvMetricV3ResponseBody) SetMac(v string) {
	o.Mac = v
}

// GetMav returns the Mav field value
func (o *EnvMetricV3ResponseBody) GetMav() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mav
}

// GetMavOk returns a tuple with the Mav field value
// and a boolean to check if the value has been set.
func (o *EnvMetricV3ResponseBody) GetMavOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mav, true
}

// SetMav sets field value
func (o *EnvMetricV3ResponseBody) SetMav(v string) {
	o.Mav = v
}

// GetMc returns the Mc field value
func (o *EnvMetricV3ResponseBody) GetMc() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mc
}

// GetMcOk returns a tuple with the Mc field value
// and a boolean to check if the value has been set.
func (o *EnvMetricV3ResponseBody) GetMcOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mc, true
}

// SetMc sets field value
func (o *EnvMetricV3ResponseBody) SetMc(v string) {
	o.Mc = v
}

// GetMpr returns the Mpr field value
func (o *EnvMetricV3ResponseBody) GetMpr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mpr
}

// GetMprOk returns a tuple with the Mpr field value
// and a boolean to check if the value has been set.
func (o *EnvMetricV3ResponseBody) GetMprOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mpr, true
}

// SetMpr sets field value
func (o *EnvMetricV3ResponseBody) SetMpr(v string) {
	o.Mpr = v
}

// GetMs returns the Ms field value
func (o *EnvMetricV3ResponseBody) GetMs() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Ms
}

// GetMsOk returns a tuple with the Ms field value
// and a boolean to check if the value has been set.
func (o *EnvMetricV3ResponseBody) GetMsOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ms, true
}

// SetMs sets field value
func (o *EnvMetricV3ResponseBody) SetMs(v string) {
	o.Ms = v
}

// GetMui returns the Mui field value
func (o *EnvMetricV3ResponseBody) GetMui() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mui
}

// GetMuiOk returns a tuple with the Mui field value
// and a boolean to check if the value has been set.
func (o *EnvMetricV3ResponseBody) GetMuiOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mui, true
}

// SetMui sets field value
func (o *EnvMetricV3ResponseBody) SetMui(v string) {
	o.Mui = v
}

// GetRoleID returns the RoleID field value
func (o *EnvMetricV3ResponseBody) GetRoleID() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.RoleID
}

// GetRoleIDOk returns a tuple with the RoleID field value
// and a boolean to check if the value has been set.
func (o *EnvMetricV3ResponseBody) GetRoleIDOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleID, true
}

// SetRoleID sets field value
func (o *EnvMetricV3ResponseBody) SetRoleID(v int64) {
	o.RoleID = v
}

// GetRoleName returns the RoleName field value
func (o *EnvMetricV3ResponseBody) GetRoleName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleName
}

// GetRoleNameOk returns a tuple with the RoleName field value
// and a boolean to check if the value has been set.
func (o *EnvMetricV3ResponseBody) GetRoleNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleName, true
}

// SetRoleName sets field value
func (o *EnvMetricV3ResponseBody) SetRoleName(v string) {
	o.RoleName = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *EnvMetricV3ResponseBody) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *EnvMetricV3ResponseBody) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *EnvMetricV3ResponseBody) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o EnvMetricV3ResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if true {
		toSerialize["cveID"] = o.CveID
	}
	if true {
		toSerialize["ma"] = o.Ma
	}
	if true {
		toSerialize["mac"] = o.Mac
	}
	if true {
		toSerialize["mav"] = o.Mav
	}
	if true {
		toSerialize["mc"] = o.Mc
	}
	if true {
		toSerialize["mpr"] = o.Mpr
	}
	if true {
		toSerialize["ms"] = o.Ms
	}
	if true {
		toSerialize["mui"] = o.Mui
	}
	if true {
		toSerialize["roleID"] = o.RoleID
	}
	if true {
		toSerialize["roleName"] = o.RoleName
	}
	if true {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableEnvMetricV3ResponseBody struct {
	value *EnvMetricV3ResponseBody
	isSet bool
}

func (v NullableEnvMetricV3ResponseBody) Get() *EnvMetricV3ResponseBody {
	return v.value
}

func (v *NullableEnvMetricV3ResponseBody) Set(val *EnvMetricV3ResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableEnvMetricV3ResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableEnvMetricV3ResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnvMetricV3ResponseBody(val *EnvMetricV3ResponseBody) *NullableEnvMetricV3ResponseBody {
	return &NullableEnvMetricV3ResponseBody{value: val, isSet: true}
}

func (v NullableEnvMetricV3ResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnvMetricV3ResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


