/*
Future Vuls Public API

Future Vuls Public API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// RoleListResponseBody struct for RoleListResponseBody
type RoleListResponseBody struct {
	// AllTaskCount of server role
	AllTaskCount *int64 `json:"allTaskCount,omitempty"`
	// created time of server role
	CreatedAt time.Time `json:"createdAt"`
	// ID of server role
	Id int64 `json:"id"`
	// isDefault of server role
	IsDefault bool `json:"isDefault"`
	// Name of server role
	Name string `json:"name"`
	// NewTaskCount of server role
	NewTaskCount *int64 `json:"newTaskCount,omitempty"`
	SecMetric *SecMetricResponseBody `json:"secMetric,omitempty"`
	// Server Count of server role
	ServerCount *int64 `json:"serverCount,omitempty"`
	// updated time of server role
	UpdatedAt time.Time `json:"updatedAt"`
}

// NewRoleListResponseBody instantiates a new RoleListResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRoleListResponseBody(createdAt time.Time, id int64, isDefault bool, name string, updatedAt time.Time) *RoleListResponseBody {
	this := RoleListResponseBody{}
	this.CreatedAt = createdAt
	this.Id = id
	this.IsDefault = isDefault
	this.Name = name
	this.UpdatedAt = updatedAt
	return &this
}

// NewRoleListResponseBodyWithDefaults instantiates a new RoleListResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRoleListResponseBodyWithDefaults() *RoleListResponseBody {
	this := RoleListResponseBody{}
	return &this
}

// GetAllTaskCount returns the AllTaskCount field value if set, zero value otherwise.
func (o *RoleListResponseBody) GetAllTaskCount() int64 {
	if o == nil || o.AllTaskCount == nil {
		var ret int64
		return ret
	}
	return *o.AllTaskCount
}

// GetAllTaskCountOk returns a tuple with the AllTaskCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleListResponseBody) GetAllTaskCountOk() (*int64, bool) {
	if o == nil || o.AllTaskCount == nil {
		return nil, false
	}
	return o.AllTaskCount, true
}

// HasAllTaskCount returns a boolean if a field has been set.
func (o *RoleListResponseBody) HasAllTaskCount() bool {
	if o != nil && o.AllTaskCount != nil {
		return true
	}

	return false
}

// SetAllTaskCount gets a reference to the given int64 and assigns it to the AllTaskCount field.
func (o *RoleListResponseBody) SetAllTaskCount(v int64) {
	o.AllTaskCount = &v
}

// GetCreatedAt returns the CreatedAt field value
func (o *RoleListResponseBody) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *RoleListResponseBody) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *RoleListResponseBody) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetId returns the Id field value
func (o *RoleListResponseBody) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *RoleListResponseBody) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *RoleListResponseBody) SetId(v int64) {
	o.Id = v
}

// GetIsDefault returns the IsDefault field value
func (o *RoleListResponseBody) GetIsDefault() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value
// and a boolean to check if the value has been set.
func (o *RoleListResponseBody) GetIsDefaultOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IsDefault, true
}

// SetIsDefault sets field value
func (o *RoleListResponseBody) SetIsDefault(v bool) {
	o.IsDefault = v
}

// GetName returns the Name field value
func (o *RoleListResponseBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RoleListResponseBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RoleListResponseBody) SetName(v string) {
	o.Name = v
}

// GetNewTaskCount returns the NewTaskCount field value if set, zero value otherwise.
func (o *RoleListResponseBody) GetNewTaskCount() int64 {
	if o == nil || o.NewTaskCount == nil {
		var ret int64
		return ret
	}
	return *o.NewTaskCount
}

// GetNewTaskCountOk returns a tuple with the NewTaskCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleListResponseBody) GetNewTaskCountOk() (*int64, bool) {
	if o == nil || o.NewTaskCount == nil {
		return nil, false
	}
	return o.NewTaskCount, true
}

// HasNewTaskCount returns a boolean if a field has been set.
func (o *RoleListResponseBody) HasNewTaskCount() bool {
	if o != nil && o.NewTaskCount != nil {
		return true
	}

	return false
}

// SetNewTaskCount gets a reference to the given int64 and assigns it to the NewTaskCount field.
func (o *RoleListResponseBody) SetNewTaskCount(v int64) {
	o.NewTaskCount = &v
}

// GetSecMetric returns the SecMetric field value if set, zero value otherwise.
func (o *RoleListResponseBody) GetSecMetric() SecMetricResponseBody {
	if o == nil || o.SecMetric == nil {
		var ret SecMetricResponseBody
		return ret
	}
	return *o.SecMetric
}

// GetSecMetricOk returns a tuple with the SecMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleListResponseBody) GetSecMetricOk() (*SecMetricResponseBody, bool) {
	if o == nil || o.SecMetric == nil {
		return nil, false
	}
	return o.SecMetric, true
}

// HasSecMetric returns a boolean if a field has been set.
func (o *RoleListResponseBody) HasSecMetric() bool {
	if o != nil && o.SecMetric != nil {
		return true
	}

	return false
}

// SetSecMetric gets a reference to the given SecMetricResponseBody and assigns it to the SecMetric field.
func (o *RoleListResponseBody) SetSecMetric(v SecMetricResponseBody) {
	o.SecMetric = &v
}

// GetServerCount returns the ServerCount field value if set, zero value otherwise.
func (o *RoleListResponseBody) GetServerCount() int64 {
	if o == nil || o.ServerCount == nil {
		var ret int64
		return ret
	}
	return *o.ServerCount
}

// GetServerCountOk returns a tuple with the ServerCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RoleListResponseBody) GetServerCountOk() (*int64, bool) {
	if o == nil || o.ServerCount == nil {
		return nil, false
	}
	return o.ServerCount, true
}

// HasServerCount returns a boolean if a field has been set.
func (o *RoleListResponseBody) HasServerCount() bool {
	if o != nil && o.ServerCount != nil {
		return true
	}

	return false
}

// SetServerCount gets a reference to the given int64 and assigns it to the ServerCount field.
func (o *RoleListResponseBody) SetServerCount(v int64) {
	o.ServerCount = &v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *RoleListResponseBody) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *RoleListResponseBody) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *RoleListResponseBody) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o RoleListResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AllTaskCount != nil {
		toSerialize["allTaskCount"] = o.AllTaskCount
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["isDefault"] = o.IsDefault
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.NewTaskCount != nil {
		toSerialize["newTaskCount"] = o.NewTaskCount
	}
	if o.SecMetric != nil {
		toSerialize["secMetric"] = o.SecMetric
	}
	if o.ServerCount != nil {
		toSerialize["serverCount"] = o.ServerCount
	}
	if true {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableRoleListResponseBody struct {
	value *RoleListResponseBody
	isSet bool
}

func (v NullableRoleListResponseBody) Get() *RoleListResponseBody {
	return v.value
}

func (v *NullableRoleListResponseBody) Set(val *RoleListResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleListResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleListResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleListResponseBody(val *RoleListResponseBody) *NullableRoleListResponseBody {
	return &NullableRoleListResponseBody{value: val, isSet: true}
}

func (v NullableRoleListResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleListResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


