/*
Future Vuls Public API

Future Vuls Public API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// DetectionToolResponseBody struct for DetectionToolResponseBody
type DetectionToolResponseBody struct {
	// Detection Tool Name
	Name string `json:"name"`
	// PatchAppliedAt
	PatchAppliedAt *time.Time `json:"patchAppliedAt,omitempty"`
}

// NewDetectionToolResponseBody instantiates a new DetectionToolResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDetectionToolResponseBody(name string) *DetectionToolResponseBody {
	this := DetectionToolResponseBody{}
	this.Name = name
	return &this
}

// NewDetectionToolResponseBodyWithDefaults instantiates a new DetectionToolResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDetectionToolResponseBodyWithDefaults() *DetectionToolResponseBody {
	this := DetectionToolResponseBody{}
	return &this
}

// GetName returns the Name field value
func (o *DetectionToolResponseBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DetectionToolResponseBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DetectionToolResponseBody) SetName(v string) {
	o.Name = v
}

// GetPatchAppliedAt returns the PatchAppliedAt field value if set, zero value otherwise.
func (o *DetectionToolResponseBody) GetPatchAppliedAt() time.Time {
	if o == nil || o.PatchAppliedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.PatchAppliedAt
}

// GetPatchAppliedAtOk returns a tuple with the PatchAppliedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DetectionToolResponseBody) GetPatchAppliedAtOk() (*time.Time, bool) {
	if o == nil || o.PatchAppliedAt == nil {
		return nil, false
	}
	return o.PatchAppliedAt, true
}

// HasPatchAppliedAt returns a boolean if a field has been set.
func (o *DetectionToolResponseBody) HasPatchAppliedAt() bool {
	if o != nil && o.PatchAppliedAt != nil {
		return true
	}

	return false
}

// SetPatchAppliedAt gets a reference to the given time.Time and assigns it to the PatchAppliedAt field.
func (o *DetectionToolResponseBody) SetPatchAppliedAt(v time.Time) {
	o.PatchAppliedAt = &v
}

func (o DetectionToolResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.PatchAppliedAt != nil {
		toSerialize["patchAppliedAt"] = o.PatchAppliedAt
	}
	return json.Marshal(toSerialize)
}

type NullableDetectionToolResponseBody struct {
	value *DetectionToolResponseBody
	isSet bool
}

func (v NullableDetectionToolResponseBody) Get() *DetectionToolResponseBody {
	return v.value
}

func (v *NullableDetectionToolResponseBody) Set(val *DetectionToolResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableDetectionToolResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableDetectionToolResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetectionToolResponseBody(val *DetectionToolResponseBody) *NullableDetectionToolResponseBody {
	return &NullableDetectionToolResponseBody{value: val, isSet: true}
}

func (v NullableDetectionToolResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetectionToolResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


