/*
Future Vuls Public API

Future Vuls Public API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CweResponseBody Cwe describes a cwe
type CweResponseBody struct {
	// cweID of cwe
	CweID string `json:"cweID"`
	// english summary of cwe
	English string `json:"english"`
	// japanese summary of cwe
	Japanese string `json:"japanese"`
	// owaspTopTen2017 of cwe 
	OwaspTopTen2017 *string `json:"owaspTopTen2017,omitempty"`
	// sourceType of cwe
	SourceType string `json:"sourceType"`
}

// NewCweResponseBody instantiates a new CweResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCweResponseBody(cweID string, english string, japanese string, sourceType string) *CweResponseBody {
	this := CweResponseBody{}
	this.CweID = cweID
	this.English = english
	this.Japanese = japanese
	this.SourceType = sourceType
	return &this
}

// NewCweResponseBodyWithDefaults instantiates a new CweResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCweResponseBodyWithDefaults() *CweResponseBody {
	this := CweResponseBody{}
	return &this
}

// GetCweID returns the CweID field value
func (o *CweResponseBody) GetCweID() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CweID
}

// GetCweIDOk returns a tuple with the CweID field value
// and a boolean to check if the value has been set.
func (o *CweResponseBody) GetCweIDOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CweID, true
}

// SetCweID sets field value
func (o *CweResponseBody) SetCweID(v string) {
	o.CweID = v
}

// GetEnglish returns the English field value
func (o *CweResponseBody) GetEnglish() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.English
}

// GetEnglishOk returns a tuple with the English field value
// and a boolean to check if the value has been set.
func (o *CweResponseBody) GetEnglishOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.English, true
}

// SetEnglish sets field value
func (o *CweResponseBody) SetEnglish(v string) {
	o.English = v
}

// GetJapanese returns the Japanese field value
func (o *CweResponseBody) GetJapanese() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Japanese
}

// GetJapaneseOk returns a tuple with the Japanese field value
// and a boolean to check if the value has been set.
func (o *CweResponseBody) GetJapaneseOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Japanese, true
}

// SetJapanese sets field value
func (o *CweResponseBody) SetJapanese(v string) {
	o.Japanese = v
}

// GetOwaspTopTen2017 returns the OwaspTopTen2017 field value if set, zero value otherwise.
func (o *CweResponseBody) GetOwaspTopTen2017() string {
	if o == nil || o.OwaspTopTen2017 == nil {
		var ret string
		return ret
	}
	return *o.OwaspTopTen2017
}

// GetOwaspTopTen2017Ok returns a tuple with the OwaspTopTen2017 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CweResponseBody) GetOwaspTopTen2017Ok() (*string, bool) {
	if o == nil || o.OwaspTopTen2017 == nil {
		return nil, false
	}
	return o.OwaspTopTen2017, true
}

// HasOwaspTopTen2017 returns a boolean if a field has been set.
func (o *CweResponseBody) HasOwaspTopTen2017() bool {
	if o != nil && o.OwaspTopTen2017 != nil {
		return true
	}

	return false
}

// SetOwaspTopTen2017 gets a reference to the given string and assigns it to the OwaspTopTen2017 field.
func (o *CweResponseBody) SetOwaspTopTen2017(v string) {
	o.OwaspTopTen2017 = &v
}

// GetSourceType returns the SourceType field value
func (o *CweResponseBody) GetSourceType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceType
}

// GetSourceTypeOk returns a tuple with the SourceType field value
// and a boolean to check if the value has been set.
func (o *CweResponseBody) GetSourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceType, true
}

// SetSourceType sets field value
func (o *CweResponseBody) SetSourceType(v string) {
	o.SourceType = v
}

func (o CweResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["cweID"] = o.CweID
	}
	if true {
		toSerialize["english"] = o.English
	}
	if true {
		toSerialize["japanese"] = o.Japanese
	}
	if o.OwaspTopTen2017 != nil {
		toSerialize["owaspTopTen2017"] = o.OwaspTopTen2017
	}
	if true {
		toSerialize["sourceType"] = o.SourceType
	}
	return json.Marshal(toSerialize)
}

type NullableCweResponseBody struct {
	value *CweResponseBody
	isSet bool
}

func (v NullableCweResponseBody) Get() *CweResponseBody {
	return v.value
}

func (v *NullableCweResponseBody) Set(val *CweResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableCweResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableCweResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCweResponseBody(val *CweResponseBody) *NullableCweResponseBody {
	return &NullableCweResponseBody{value: val, isSet: true}
}

func (v NullableCweResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCweResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


