/*
Future Vuls Public API

Future Vuls Public API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// LibraryPkgChildResponseBody struct for LibraryPkgChildResponseBody
type LibraryPkgChildResponseBody struct {
	// crated time of package or cpe
	CreatedAt time.Time `json:"createdAt"`
	// ID of library package
	Id int64 `json:"id"`
	// Name of library package
	Name string `json:"name"`
	// updated time of package or cpe
	UpdatedAt time.Time `json:"updatedAt"`
	// Version of library package
	Version string `json:"version"`
}

// NewLibraryPkgChildResponseBody instantiates a new LibraryPkgChildResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLibraryPkgChildResponseBody(createdAt time.Time, id int64, name string, updatedAt time.Time, version string) *LibraryPkgChildResponseBody {
	this := LibraryPkgChildResponseBody{}
	this.CreatedAt = createdAt
	this.Id = id
	this.Name = name
	this.UpdatedAt = updatedAt
	this.Version = version
	return &this
}

// NewLibraryPkgChildResponseBodyWithDefaults instantiates a new LibraryPkgChildResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLibraryPkgChildResponseBodyWithDefaults() *LibraryPkgChildResponseBody {
	this := LibraryPkgChildResponseBody{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *LibraryPkgChildResponseBody) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *LibraryPkgChildResponseBody) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *LibraryPkgChildResponseBody) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetId returns the Id field value
func (o *LibraryPkgChildResponseBody) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *LibraryPkgChildResponseBody) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *LibraryPkgChildResponseBody) SetId(v int64) {
	o.Id = v
}

// GetName returns the Name field value
func (o *LibraryPkgChildResponseBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *LibraryPkgChildResponseBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *LibraryPkgChildResponseBody) SetName(v string) {
	o.Name = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *LibraryPkgChildResponseBody) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *LibraryPkgChildResponseBody) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *LibraryPkgChildResponseBody) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetVersion returns the Version field value
func (o *LibraryPkgChildResponseBody) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *LibraryPkgChildResponseBody) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *LibraryPkgChildResponseBody) SetVersion(v string) {
	o.Version = v
}

func (o LibraryPkgChildResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if true {
		toSerialize["version"] = o.Version
	}
	return json.Marshal(toSerialize)
}

type NullableLibraryPkgChildResponseBody struct {
	value *LibraryPkgChildResponseBody
	isSet bool
}

func (v NullableLibraryPkgChildResponseBody) Get() *LibraryPkgChildResponseBody {
	return v.value
}

func (v *NullableLibraryPkgChildResponseBody) Set(val *LibraryPkgChildResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableLibraryPkgChildResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableLibraryPkgChildResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLibraryPkgChildResponseBody(val *LibraryPkgChildResponseBody) *NullableLibraryPkgChildResponseBody {
	return &NullableLibraryPkgChildResponseBody{value: val, isSet: true}
}

func (v NullableLibraryPkgChildResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLibraryPkgChildResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


