/*
Future Vuls Public API

Future Vuls Public API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// DetectionMethodResponseBody struct for DetectionMethodResponseBody
type DetectionMethodResponseBody struct {
	// Detection Method Name
	Name string `json:"name"`
	// ReliabilityScore
	ReliabilityScore int64 `json:"reliabilityScore"`
}

// NewDetectionMethodResponseBody instantiates a new DetectionMethodResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDetectionMethodResponseBody(name string, reliabilityScore int64) *DetectionMethodResponseBody {
	this := DetectionMethodResponseBody{}
	this.Name = name
	this.ReliabilityScore = reliabilityScore
	return &this
}

// NewDetectionMethodResponseBodyWithDefaults instantiates a new DetectionMethodResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDetectionMethodResponseBodyWithDefaults() *DetectionMethodResponseBody {
	this := DetectionMethodResponseBody{}
	return &this
}

// GetName returns the Name field value
func (o *DetectionMethodResponseBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *DetectionMethodResponseBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *DetectionMethodResponseBody) SetName(v string) {
	o.Name = v
}

// GetReliabilityScore returns the ReliabilityScore field value
func (o *DetectionMethodResponseBody) GetReliabilityScore() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ReliabilityScore
}

// GetReliabilityScoreOk returns a tuple with the ReliabilityScore field value
// and a boolean to check if the value has been set.
func (o *DetectionMethodResponseBody) GetReliabilityScoreOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReliabilityScore, true
}

// SetReliabilityScore sets field value
func (o *DetectionMethodResponseBody) SetReliabilityScore(v int64) {
	o.ReliabilityScore = v
}

func (o DetectionMethodResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["reliabilityScore"] = o.ReliabilityScore
	}
	return json.Marshal(toSerialize)
}

type NullableDetectionMethodResponseBody struct {
	value *DetectionMethodResponseBody
	isSet bool
}

func (v NullableDetectionMethodResponseBody) Get() *DetectionMethodResponseBody {
	return v.value
}

func (v *NullableDetectionMethodResponseBody) Set(val *DetectionMethodResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullableDetectionMethodResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullableDetectionMethodResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDetectionMethodResponseBody(val *DetectionMethodResponseBody) *NullableDetectionMethodResponseBody {
	return &NullableDetectionMethodResponseBody{value: val, isSet: true}
}

func (v NullableDetectionMethodResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDetectionMethodResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


