/*
Future Vuls Public API

Future Vuls Public API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PkgCpeGetPkgCpeListResponseBody struct for PkgCpeGetPkgCpeListResponseBody
type PkgCpeGetPkgCpeListResponseBody struct {
	Paging *PagingResponseBody `json:"paging,omitempty"`
	// PkgCpes list
	PkgCpes []PkgCpeListResponseBody `json:"pkgCpes,omitempty"`
}

// NewPkgCpeGetPkgCpeListResponseBody instantiates a new PkgCpeGetPkgCpeListResponseBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPkgCpeGetPkgCpeListResponseBody() *PkgCpeGetPkgCpeListResponseBody {
	this := PkgCpeGetPkgCpeListResponseBody{}
	return &this
}

// NewPkgCpeGetPkgCpeListResponseBodyWithDefaults instantiates a new PkgCpeGetPkgCpeListResponseBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPkgCpeGetPkgCpeListResponseBodyWithDefaults() *PkgCpeGetPkgCpeListResponseBody {
	this := PkgCpeGetPkgCpeListResponseBody{}
	return &this
}

// GetPaging returns the Paging field value if set, zero value otherwise.
func (o *PkgCpeGetPkgCpeListResponseBody) GetPaging() PagingResponseBody {
	if o == nil || o.Paging == nil {
		var ret PagingResponseBody
		return ret
	}
	return *o.Paging
}

// GetPagingOk returns a tuple with the Paging field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PkgCpeGetPkgCpeListResponseBody) GetPagingOk() (*PagingResponseBody, bool) {
	if o == nil || o.Paging == nil {
		return nil, false
	}
	return o.Paging, true
}

// HasPaging returns a boolean if a field has been set.
func (o *PkgCpeGetPkgCpeListResponseBody) HasPaging() bool {
	if o != nil && o.Paging != nil {
		return true
	}

	return false
}

// SetPaging gets a reference to the given PagingResponseBody and assigns it to the Paging field.
func (o *PkgCpeGetPkgCpeListResponseBody) SetPaging(v PagingResponseBody) {
	o.Paging = &v
}

// GetPkgCpes returns the PkgCpes field value if set, zero value otherwise.
func (o *PkgCpeGetPkgCpeListResponseBody) GetPkgCpes() []PkgCpeListResponseBody {
	if o == nil || o.PkgCpes == nil {
		var ret []PkgCpeListResponseBody
		return ret
	}
	return o.PkgCpes
}

// GetPkgCpesOk returns a tuple with the PkgCpes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PkgCpeGetPkgCpeListResponseBody) GetPkgCpesOk() ([]PkgCpeListResponseBody, bool) {
	if o == nil || o.PkgCpes == nil {
		return nil, false
	}
	return o.PkgCpes, true
}

// HasPkgCpes returns a boolean if a field has been set.
func (o *PkgCpeGetPkgCpeListResponseBody) HasPkgCpes() bool {
	if o != nil && o.PkgCpes != nil {
		return true
	}

	return false
}

// SetPkgCpes gets a reference to the given []PkgCpeListResponseBody and assigns it to the PkgCpes field.
func (o *PkgCpeGetPkgCpeListResponseBody) SetPkgCpes(v []PkgCpeListResponseBody) {
	o.PkgCpes = v
}

func (o PkgCpeGetPkgCpeListResponseBody) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Paging != nil {
		toSerialize["paging"] = o.Paging
	}
	if o.PkgCpes != nil {
		toSerialize["pkgCpes"] = o.PkgCpes
	}
	return json.Marshal(toSerialize)
}

type NullablePkgCpeGetPkgCpeListResponseBody struct {
	value *PkgCpeGetPkgCpeListResponseBody
	isSet bool
}

func (v NullablePkgCpeGetPkgCpeListResponseBody) Get() *PkgCpeGetPkgCpeListResponseBody {
	return v.value
}

func (v *NullablePkgCpeGetPkgCpeListResponseBody) Set(val *PkgCpeGetPkgCpeListResponseBody) {
	v.value = val
	v.isSet = true
}

func (v NullablePkgCpeGetPkgCpeListResponseBody) IsSet() bool {
	return v.isSet
}

func (v *NullablePkgCpeGetPkgCpeListResponseBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePkgCpeGetPkgCpeListResponseBody(val *PkgCpeGetPkgCpeListResponseBody) *NullablePkgCpeGetPkgCpeListResponseBody {
	return &NullablePkgCpeGetPkgCpeListResponseBody{value: val, isSet: true}
}

func (v NullablePkgCpeGetPkgCpeListResponseBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePkgCpeGetPkgCpeListResponseBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


